version: '3.7'
services:
  app:
    image: www
    container_name: www
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: 'laravelapp'
    ports: 
      - "8080:80"
    volumes: 
      - ./htdocs:/var/www/html
      - ./docker/init-scripts/:/init-scripts/
    depends_on:
      - 'mysql'
    entrypoint:
      - /init-scripts/apache_start.sh
  mysql:
    container_name: mysql
    image: mysql:5.7
    # restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: 'lara_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8081:80'
    environment:
      - 'PMA_HOST=mysql'
    depends_on:
      - 'mysql'  
  node:
    image: node:15-alpine
    container_name: node
    working_dir: /usr/src/app
    volumes:
      - ./htdocs:/usr/src/app
      - ./docker/init-scripts/:/init-scripts/
    entrypoint:
      - /init-scripts/node_start.sh
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - 'app'
volumes:
  mysql:
    driver: "local"
